# Translations template for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-05-19 21:44+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:39
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:68
msgid "Email"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:40
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:57
msgid "User ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:41
#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:75
#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:108
msgid "Deny"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:74
msgid "Role Name"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:107
msgid "System Role"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:136
#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:143
#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:150
#: .venv/lib/python3.13/site-packages/invenio_oauth2server/admin.py:70
#: .venv/lib/python3.13/site-packages/invenio_oauth2server/admin.py:79
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:92
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:100
msgid "User Management"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:137
msgid "Access: Roles"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:144
msgid "Access: Users"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_access/admin.py:151
msgid "Access: System Roles"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_audit_logs/services/config.py:44
#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:36
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:35
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:100
msgid "Ascending"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_audit_logs/services/config.py:45
#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:40
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:39
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:101
msgid "Descending"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_audit_logs/services/config.py:60
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:66
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:160
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:202
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:43
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:86
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:117
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:54
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:83
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:225
#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/config.py:35
#: .venv/lib/python3.13/site-packages/invenio_records_rest/config.py:267
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:60
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:154
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/groups/config.py:44
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/config.py:57
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/config.py:56
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/config.py:51
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/subjects/config.py:66
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:67
msgid "Best match"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_audit_logs/services/config.py:61
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:70
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:168
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:210
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:94
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:125
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:58
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:95
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:229
#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/config.py:39
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:76
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:162
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/config.py:65
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/config.py:64
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/config.py:59
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/subjects/config.py:74
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:75
msgid "Newest"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_audit_logs/services/config.py:62
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:74
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:172
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:214
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:98
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:129
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:62
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:99
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:233
#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/config.py:43
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:80
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:166
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/config.py:69
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/config.py:68
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/config.py:63
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/subjects/config.py:78
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:79
msgid "Oldest"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:16
msgid "Info"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:17
msgid "Warning"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:18
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:109
msgid "Other"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:43
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:86
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:178
#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:38
msgid "URL path"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:42
msgid "Start DateTime"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:46
msgid "End DateTime"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:42
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:113
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:180
#: .venv/lib/python3.13/site-packages/invenio_banners/config.py:50
#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:60
msgid "Active"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:26
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:27
msgid "Banners"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:28
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:30
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/administration/views/vocabularies.py:25
msgid "Site management"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:38
msgid "Id"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:39
msgid "Start time (UTC)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:40
msgid "End time (UTC)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:41
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:78
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:177
msgid "Message"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:44
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:98
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:179
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:38
msgid "Category"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:56
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:175
#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:52
msgid "Start time"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:58
msgid ""
"Date/time to make the banner active. Input format: yyyy-mm-dd hh:mm:ss. "
"Set to future date/time to delay the banner. Note: specify time in UTC "
"time standard."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:63
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:74
msgid "YYYY-MM-DD hh:mm:ss"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:67
#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:176
#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:56
msgid "End time"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:69
msgid ""
"Date/time to make the banner inactive. Input format: yyyy-mm-dd hh:mm:ss."
"  An empty value makes the banner active until manually disabled via the "
"active flag. Note: specify time in UTC time standard."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:80
msgid "Message to be displayed on the banner. HTML format is supported."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:88
msgid ""
"URL path prefix (including the first /) to define where the message will "
"be active on the site. For example, if you enter `/records`, any URL "
"starting with `/records` will return an active banner (`/records`, "
"`/records/1234`, etc.). An empty value makes the banner active for any "
"URL."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:100
msgid ""
"Banner category. `Info` option displays a blue banner. `Warning` option "
"displays an orange banner. `Other` option displays a gray banner."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:115
msgid ""
"Tick it to activate the banner: banner will be displayed according to "
"start/end times. If not activated, start/end times will be ignored."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:131
msgid "Edit Banner"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:150
msgid "Create Banner"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:166
msgid "Banner Details"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:181
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:43
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:153
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:337
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:54
msgid "Created"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/administration/banners.py:182
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:44
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:154
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:341
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:58
msgid "Updated"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_banners/services/config.py:48
msgid "Url path"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:78
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:66
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:103
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:120
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:194
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:237
msgid "Version"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:82
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:87
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:241
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:84
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:170
msgid "Recently updated"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:86
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/config.py:91
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:245
msgid "Least recently updated"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:39
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:96
msgid "Reader"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:97
msgid "Can view restricted records."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:41
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:102
msgid "Curator"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:103
msgid "Can curate records and view restricted records."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:40
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:109
msgid "Manager"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:111
msgid "Can manage members, curate records and view restricted records."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:38
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:120
msgid "Owner"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:121
msgid "Full administrative access to the entire community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:164
#: .venv/lib/python3.13/site-packages/invenio_communities/config.py:206
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:47
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:90
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/config.py:121
#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:121
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:46
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/groups/config.py:48
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/administration/views/vocabularies.py:37
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:175
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/config.py:61
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/config.py:60
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/config.py:55
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/subjects/config.py:70
msgid "Name"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/errors.py:29
#, python-brace-format
msgid "A featured community entry with {q} does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/errors.py:41
msgid "No logo exists for this community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/errors.py:53
#, python-brace-format
msgid ""
"Logo size limit exceeded. Limit: {limit_value} {limit_unit} Given: "
"{file_size_value} {file_size_unit}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/errors.py:70
#, python-format
msgid ""
"There is %(num)s request open for this community. Please, resolve it "
"before deleting this community."
msgid_plural ""
"There are %(num)s requests open for this community. Please, resolve all "
"of them before deleting this community."
msgstr[0] ""
msgstr[1] ""

#: .venv/lib/python3.13/site-packages/invenio_communities/errors.py:102
msgid ""
"Cannot set community as the default. The record has not been added to the"
" community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:147
msgid "Communities"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:152
msgid "New community"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:161
msgid "Requests"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:168
msgid "Members"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:176
msgid "Settings"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:184
msgid "Curation policy"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/ext.py:192
msgid "About"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/roles.py:64
msgid "Only one role be defined as owner."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/roles.py:66
msgid "One role must be defined as owner."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:55
#, python-brace-format
msgid "Field cannot be blank or longer than {max_} characters."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:65
#, python-brace-format
msgid "Field cannot be longer than {max} characters."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:76
msgid "The ID must not be an Universally Unique IDentifier (UUID)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:245
msgid "The identifier should contain only letters, numbers, or dashes."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:337
msgid "start date"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:338
msgid "Accepted format: YYYY-MM-DD hh:mm"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:349
msgid "Deleted community"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/schema.py:350
msgid "The community was deleted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/resources/config.py:70
#: .venv/lib/python3.13/site-packages/invenio_communities/members/resources/config.py:56
#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:138
msgid "The record has been deleted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/resources/ui_schema.py:50
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/schema.py:104
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/github/release.py:60
msgid "Unknown"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/resources/ui_schema.py:57
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/schema.py:111
msgid "System (automatic)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/resources/ui_schema.py:59
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/schema.py:113
msgid "Admin"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:40
msgid "A community with this identifier already exists."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:58
msgid "The ID should be modified through the renaming URL instead."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:66
msgid "A new ID value is required for the renaming."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:148
msgid "The community is not public."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:177
#, python-format
msgid "parent.communities.ids:%(id)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:320
msgid "Assigned parent is not allowed to be a parent."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:324
msgid "Community allowed to be a parent can't be a child."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:328
msgid "Assigned parent community cannot also have a parent."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:332
msgid "Assigned parent community cannot be the same as child."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/components.py:335
msgid "Assigned parent community does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/config.py:58
msgid "Featured"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:16
msgid "Type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:18
msgid "Organization"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:19
msgid "Event"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:20
msgid "Topic"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:21
msgid "Project"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:27
#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:36
#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:47
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:36
msgid "Visibility"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:29
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:37
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:32
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:49
#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:165
#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:206
#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:219
msgid "Public"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:30
#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:50
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:40
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:37
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:34
msgid "Restricted"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/facets.py:49
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:37
#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:207
#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:220
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:51
msgid "Hidden"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/communities/services/service.py:209
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/deserializers/rocrate/schema.py:32
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:363
msgid "Missing data for required field."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/resources/config.py:44
msgid "Invalid member specified."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/resources/config.py:50
msgid "A member was already added or invited."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/components.py:34
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/components.py:43
msgid "Community must be defined."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/components.py:49
#, python-format
msgid "Member must be 'MemberMixin' or 'dict' but was %(type)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:18
msgid "Role"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:24
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:42
#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:69
#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:80
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:42
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:16
msgid "Status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:26
msgid "Submitted"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:27
msgid "Expired"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:28
msgid "Accepted"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:29
msgid "Declined"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:30
msgid "Cancelled"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:43
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:70
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:113
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:35
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:32
msgid "Open"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/facets.py:43
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:79
#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:119
msgid "Closed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/fields.py:22
msgid "Invalid role."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/fields.py:45
msgid "Not a valid role to serialize."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/request.py:108
msgid "Community invitation"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/request.py:153
msgid "Membership request"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/schemas.py:89
msgid "Missing fields 'role' and/or 'visible'."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/schemas.py:123
msgid "Untitled"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:203
msgid "Must be false"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:225
msgid "Invalid member type: email"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:284
#, python-format
msgid "Invitation to join \"%(community)s\""
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:287
#, python-format
msgid "You will join as \"%(role)s\"."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:544
#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:664
msgid "A community must have at least one owner."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:573
msgid "You cannot change your own role."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:581
msgid "You can only set public visibility on your own membership."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:590
#, python-format
msgid "You will join as \"%(role)s\" (changed from: \"%(previous)s\")."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/members/services/service.py:766
#, python-format
msgid "Request to join \"%(community)s\""
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/requests/user_moderation/actions.py:74
msgid "User was blocked"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/subcommunities/services/request.py:64
msgid "Subcommunity request"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/subcommunities/services/request.py:151
msgid "Subcommunity invitation"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/subcommunities/services/schema.py:50
msgid "Either community_id or community should be provided."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/subcommunities/services/service.py:85
msgid "Parent community does not accept subcommunities."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/subcommunities/services/service.py:114
#, python-format
msgid "Inclusion of subcommunity \"%(community)s\""
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:36
msgid "Your community is publicly accessible and shows up in search results."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:43
msgid "Your community is restricted to users with access."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:53
msgid ""
"Members who have set their visibility to public are visible to anyone. "
"Members with hidden visibility are only visible to other members."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:58
msgid "Members-only"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:62
msgid ""
"Members in your community are only visible to other members of the "
"community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:74
msgid ""
"All authenticated users can submit records to the community. If the "
"community is restricted, then only members can submit records to it."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:82
msgid "Only members can submit records to the community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:88
msgid "Review all submissions"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:91
msgid "All submissions to the community must be reviewed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:94
msgid "Allow curators, managers and owners to publish without review"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:98
msgid ""
"Submissions to the community by default requires review, but curators, "
"managers and owners can publish directly without review."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:102
msgid "Allow all members to publish without review"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:106
msgid ""
"Submissions to the community by default requires review, but all "
"community members can publish directly without review."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:116
msgid "Users can request to join your community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_communities/views/communities.py:123
msgid ""
"Users cannot request to join your community. Only invited users can "
"become members of your community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/resources/records/errors.py:33
msgid "Redirecting..."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/service.py:104
msgid "Records should be updated via their draft."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/service.py:250
msgid "Failed to fetch the record versions."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/service.py:566
msgid "Files support is not enabled."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:87
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:118
msgid "You don't have permissions to manage files options."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:135
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:252
#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/media_files.py:64
msgid ""
"Missing uploaded files. To disable files for this record please mark it "
"as metadata-only."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:138
msgid "Missing uploaded files."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:262
msgid "One or more files have not completed their transfer, please wait."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:288
msgid "Files support must be enabled."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:294
msgid "Please remove all files first."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_drafts_resources/services/records/components/base.py:300
msgid "The record has no files."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:41
msgid "Invalid location name."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:68
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:279
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:368
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:56
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:90
msgid "ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:69
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:196
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:280
msgid "URI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:133
#: .venv/lib/python3.13/site-packages/invenio_records/admin.py:42
msgid "UUID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:134
msgid "Location"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:135
msgid "Storage Class"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:195
msgid "File UUID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:197
msgid "Size"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:198
#: .venv/lib/python3.13/site-packages/invenio_github/models.py:43
#: .venv/lib/python3.13/site-packages/invenio_pidstore/models.py:42
msgid "Deleted"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:199
msgid "Checksum"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:200
msgid "Readable"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:201
msgid "Storage class"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:202
msgid "Objects"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:203
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:370
msgid "File"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:281
msgid "Fixity"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:282
msgid "Checked"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:334
msgid "Run fixity check"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:342
msgid "Cannot find file instance."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:346
msgid "Fixity check(s) sent to queue."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:351
msgid "Failed to run fixity checks."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:369
msgid "Complete"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:397
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:399
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:401
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:404
#: .venv/lib/python3.13/site-packages/invenio_files_rest/admin.py:407
msgid "Files"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_github/ext.py:96
#, python-format
msgid "%(icon)s GitHub"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_github/models.py:39
msgid "Received"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_github/models.py:40
msgid "Processing"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_github/models.py:41
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:43
msgid "Published"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_github/models.py:42
msgid "Failed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_notifications/ext.py:68
#, python-format
msgid "%(icon)s Notifications"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_notifications/ext.py:76
msgid "Notifications"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/admin.py:56
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:65
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:105
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:146
msgid "OAI-PMH"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/admin.py:57
msgid "Sets"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:33
msgid "Identifier"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:34
msgid "Identifier of the set."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:42
msgid "Long name"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:43
msgid "Long name of the set."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:53
#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:132
msgid "Description"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:54
msgid "Description of the set."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:63
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/schema.py:30
msgid "Search pattern"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:64
msgid "Search pattern to select records"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:73
msgid "System created"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:74
msgid "System created set"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/models.py:83
msgid "Updating spec is not allowed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/percolator.py:141
msgid ""
"Either documents or (document_search_ids and document_search_indices) "
"must be specified."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/verbs.py:33
msgid "metadataPrefix does not exist"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/verbs.py:93
#, python-format
msgid "This is not a valid OAI-PMH verb:%(verb)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/verbs.py:99
msgid "Date \"from\" must be before \"until\"."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oaiserver/verbs.py:168
msgid "You have passed too many arguments."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/admin.py:69
msgid "OAuth Applications"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/admin.py:78
msgid "OAuth Application Tokens"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/ext.py:348
#, python-format
msgid "%(icon)s Applications"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:104
#, python-brace-format
msgid "Invalid redirect URIs: {urls}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:136
msgid "Redirect URIs (one per line)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:138
msgid ""
"One redirect URI per line. This is your application's authorization "
"callback URLs. HTTPS must be used for all hosts except localhost (for "
"testing purposes)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:156
msgid "Client type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:158
msgid ""
"Select confidential if your application is capable of keeping the issued "
"client secret confidential (e.g. a web application), select public if "
"your application cannot (e.g. a browser-based JavaScript application). If"
" you select public, your application MUST validate the redirect URI."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:165
msgid "Confidential"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:175
msgid "Name of personal access token."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:179
msgid "The name must be less than 40 characters long."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/forms.py:188
msgid ""
"Scopes assign permissions to your personal access token. A personal "
"access token works just like a normal OAuth  access token for "
"authentication against the API."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:122
msgid "Name of application (displayed to users)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:134
msgid "Optional. Description of the application (displayed to users)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:143
msgid "Website URL"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/models.py:144
msgid "URL of your application (displayed to users)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauth2server/scopes.py:19
msgid "Allow access to email address (read-only)."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:58
msgid "Client ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:85
msgid "ID Remote Account"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:93
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/ext.py:260
msgid "Linked accounts"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/admin.py:101
msgid "Linked account tokens"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/ext.py:250
#, python-format
msgid "%(icon)s Linked accounts"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/contrib/cern.py:438
#: .venv/lib/python3.13/site-packages/invenio_oauthclient/contrib/cern_openid.py:300
msgid "CERN account not allowed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/handlers/ui.py:60
msgid "External service is already linked to another account."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/handlers/ui.py:65
msgid "You rejected the authentication request."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_oauthclient/handlers/ui.py:240
msgid "Authorization with remote service failed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:33
msgid "View"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:66
msgid "PID Type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:67
msgid "PID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:68
msgid "Provider"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:70
msgid "Object Type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:71
#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:77
msgid "Object UUID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/admin.py:93
#: .venv/lib/python3.13/site-packages/invenio_records/admin.py:79
msgid "Records"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/models.py:38
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:18
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:23
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:39
msgid "New"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/models.py:39
msgid "Reserved"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/models.py:40
msgid "Registered"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_pidstore/models.py:41
msgid "Redirected"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_previewer/extensions/ipynb.py:38
msgid "Error: Not a ipynb/json file"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_previewer/extensions/xml_prismjs.py:32
#, python-brace-format
msgid "Error decoding the file. Are you sure it is '{encoding}'?"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:68
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:124
msgid "ORCID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:69
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:98
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:46
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:125
msgid "ISNI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:70
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:45
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:126
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:131
msgid "GND"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:71
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:47
msgid "ROR"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:75
msgid "ARK"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:76
msgid "arXiv"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:78
msgid "Bibcode"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:83
msgid "Crossref Funder ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:87
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:361
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:368
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:391
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:75
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:84
msgid "DOI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:88
msgid "EAN13"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:89
msgid "EISSN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:90
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:44
msgid "GRID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:92
msgid "Handle"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:96
msgid "IGSN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:97
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:86
msgid "ISBN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:99
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:104
msgid "ISSN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:100
msgid "ISTC"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:101
msgid "LISSN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:102
msgid "LSID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:103
msgid "PMID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:104
msgid "PURL"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:105
msgid "UPC"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:106
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:83
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:132
msgid "URL"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:107
msgid "URN"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:108
msgid "W3ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:114
msgid "Wikidata"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:115
msgid "GeoNames"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:249
msgid "Most viewed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:252
msgid "Most downloaded"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:41
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:70
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:110
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:150
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:329
msgid "Set name"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:40
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:75
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:115
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:151
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:333
msgid "Set spec"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:373
msgid "OAI ID"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:400
msgid "OAI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:420
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/config.py:430
msgid "Concept DOI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/utils.py:117
msgid "Your shared link has expired."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:29
msgid "OAI-PMH Sets"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:42
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:83
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:123
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:152
msgid "Search query"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:63
msgid "Edit OAI-PMH set"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:71
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:111
msgid "A short human-readable string naming the set."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:77
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:117
msgid ""
"An identifier for the set, which cannot be edited after the set is "
"created."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:85
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:125
msgid ""
"See the supported query syntax in the <a href='/help/search'>Search "
"Guide</a>."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:103
msgid "Create OAI-PMH set"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/administration/views/oai.py:140
msgid "OAI-PMH Details"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:36
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:46
msgid "You must provide a valid URL."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:54
msgid "Software"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:61
msgid "Repository URL"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:63
msgid "URL or link where the code repository is hosted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:70
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:111
msgid "Programming language"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:72
msgid "Repository's programming language."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:73
msgid "e.g. Python ..."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:85
msgid "Development Status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:86
msgid "Repository status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:88
msgid "Repository current status."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/codemeta/custom_fields.py:101
msgid "Development status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:36
msgid "Please provide a valid ISBN."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:72
msgid "Book / Report / Chapter"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:79
msgid "Imprint (Book, Chapter, or Report)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:81
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:118
msgid "Place"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:82
msgid "e.g. city, country"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:83
msgid "Place where the book or report was published"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:87
msgid "e.g. 0-06-251587-X"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:88
msgid "International Standard Book Number"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:91
msgid "Book or report title"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:94
msgid "Title of the book or report which this upload is part of"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:98
msgid "Pagination"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:99
msgid "e.g. 15-23 or 158"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:103
msgid "Edition"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:104
msgid "e.g. 3"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/imprint/custom_fields.py:105
msgid "The edition of the book"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:38
msgid "Please provide a valid ISSN."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:73
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:80
msgid "Journal"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:82
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:103
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/config.py:71
msgid "Title"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:85
msgid "Title of the journal in which the article was published"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:89
msgid "Volume"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:90
msgid "e.g. 645"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:94
msgid "Issue"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:95
msgid "e.g. 7"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:99
msgid "Page range or article number"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:100
msgid "e.g. 15-23 or A29"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:105
msgid "e.g. 2077-9550"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/custom_fields.py:106
msgid "International Standard Serial Number"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/journal/sort.py:14
msgid "Journal [Newest]"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:95
msgid "Conference"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:108
msgid "Acronym"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:113
msgid "Dates"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:114
msgid "e.g. 21-22 November 2022."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:120
msgid "Location where the conference took place."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:123
msgid "Identifiers"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:124
msgid "URL of conference website or other identifier."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:127
msgid "Session"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:128
msgid "e.g. VI"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:129
msgid "Session within the conference."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:132
msgid "Part"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:133
msgid "e.g. 1"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/custom_fields.py:134
msgid "Part within the session."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/meeting/sort.py:14
msgid "Conference session [Newest]"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:63
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:69
msgid "Thesis"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:72
msgid "Awarding university"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:77
msgid "Awarding department"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:82
msgid "Thesis type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:83
msgid "PhD"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:85
msgid "The type of thesis (e.g. Masters, PhD, Engineers, Bachelors)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:89
msgid "Submission date"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:91
msgid "Submission date in YYYY-MM-DD format."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:94
msgid "Defense date"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/contrib/thesis/custom_fields.py:96
msgid "Defense date in YYYY-MM-DD format."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/jobs/jobs.py:21
msgid "Updates expired embargoes"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/jobs/jobs.py:22
msgid "Update expired embargoes"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/config.py:50
msgid "Spec"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/errors.py:30
#, python-brace-format
msgid "A set where {query_arguments} does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/errors.py:43
#, python-brace-format
msgid "A set with id {id} does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/errors.py:53
#, python-brace-format
msgid "A set with spec '{spec}' already exists."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/errors.py:63
#, python-brace-format
msgid "The set with id {id} is not editable."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/services.py:101
#, python-brace-format
msgid "The spec must not start with any of the following list '{prefix}'."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/oaiserver/services/services.py:113
#, python-brace-format
msgid "The spec must only consist of letters, numbers or {marks}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/records/systemfields/draft_status.py:83
#, python-brace-format
msgid "Unknown draft status for review: {reviewstatus}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/records/systemfields/draft_status.py:89
msgid "Unknown draft status."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/community_inclusion.py:101
msgid "Community inclusion"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/community_submission.py:182
msgid "Community submission"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/access/requests.py:190
#, python-format
msgid "Click <a href=\"%(url)s\">here</a> to access the record."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/access/requests.py:250
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/access/requests.py:282
msgid "Access request"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/access/requests.py:319
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/requests/access/requests.py:324
msgid "Not a valid number of days."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:149
msgid "Citation string style not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:155
msgid "Review for draft not found"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:193
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:288
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:337
msgid "Record not found"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:197
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:292
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:341
msgid "Record deleted"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:211
msgid "Cannot publish without selecting a community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:389
msgid "No secret link found with the given ID."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:397
msgid "No grant found with the given ID."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:410
msgid "No grant found by given user id."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/config.py:417
msgid "No grant found by given group id."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/iiif.py:99
msgid "Image size limit exceeded"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/iiif.py:106
msgid ""
"The record associated with this file has been deleted. See deletion "
"notice."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/deserializers/rocrate/__init__.py:31
msgid "Invalid RO-Crate metadata format, missing '@graph' key."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/deserializers/rocrate/schema.py:102
msgid "'@type' must be 'Person' or 'Organization'"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/deserializers/rocrate/schema.py:138
msgid "Format must be a list of strings."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/utils.py:38
#, python-format
msgid "The '%(vocabulary)s' vocabulary item '%(id_)s' was not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/cff/schema.py:29
msgid "One of 'family-names' or 'given-names' is required."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/datacite/schema.py:281
msgid "Invalid publication date value."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/iiif/schema.py:167
msgid "Current Page Order"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/iiif/schema.py:194
msgid "Manifest generated by InvenioRDM"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/iiif/schema.py:213
msgid "Publication Date"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/schemaorg/schema.py:123
msgid "Affiliation failed to serialize: one of 'id' or 'name' must be provided."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/schemaorg/schema.py:369
msgid ""
"Funding serialization failed on award: one of 'id' or ('number' and "
"'title') are required."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:36
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:33
msgid "Embargoed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:38
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:35
msgid "Metadata-only"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:65
msgid "The record and files are publicly accessible."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:67
msgid "No files are available for this record."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:76
#, python-format
msgid "The record and files will be made publicly available on %(date)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:81
msgid "The record and files are restricted to users with access."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:90
#, python-format
msgid "The record will be made publicly available on %(date)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:94
msgid "The record is restricted to users with access."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:102
#, python-format
msgid "The files will be made publicly available on %(date)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/fields.py:106
msgid ""
"The record is publicly accessible, but files are restricted to users with"
" access."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/schema.py:298
msgid "Submitted: "
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/resources/serializers/ui/schema.py:299
msgid "Defended: "
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:22
msgid "Grant for this user/role already exists within this record."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:54
#, python-format
msgid "Embargo could not be lifted for record: %(record_id)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:66
msgid "Review not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:84
msgid "The record is already included in this community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:94
msgid "A public record cannot be included in a restricted community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:107
msgid "There is already an open inclusion request for this community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:163
#, python-format
msgid "The record %(rec_id)s in not included in the community %(com_id)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:179
#, python-format
msgid "Cannot modify community visibility: %(reason)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:198
#, python-format
msgid "Identical access requests already exist: %(request_id)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:202
msgid "The access request is a duplicate"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:209
msgid "Submission to this community is only allowed to community members."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:216
msgid "Cannot publish without a community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/errors.py:222
msgid "A record should be part of at least 1 community."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:30
msgid "Access status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:43
msgid "Unpublished"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:49
msgid "File type"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:56
msgid "Languages"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:65
msgid "Resource types"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:82
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:92
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/facets.py:108
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/custom_fields/subject.py:50
msgid "Subjects"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/services.py:636
msgid ""
"Record visibility can not be changed to restricted anymore. Please "
"contact support if you still need to make these changes."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:140
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:174
msgid "Expiration date must be set to the future"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:168
msgid "Cannot postpone expiration of links"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:195
msgid "An access permission level is required"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:210
msgid "Invalid access permission level."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:423
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:529
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:951
msgid "Could not find the specified subject."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/access/service.py:746
msgid "Verification link sent out, please check your e-mail inbox"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/communities/components.py:52
msgid "Cannot restrict a community with public records."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/communities/service.py:189
msgid "Community not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/communities/service.py:425
msgid "Community already included."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/community_inclusion/service.py:45
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/community_inclusion/service.py:59
msgid "Invalid request type."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/community_inclusion/service.py:78
msgid ""
"This request has been automatically accepted, as the uploader can submit "
"to community directly without review."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/community_records/service.py:138
msgid "The record does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/community_records/service.py:145
#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:126
#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:132
#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:36
msgid "Permission denied."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/components/access.py:39
msgid "You don't have permissions to manage record access."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/components/pids.py:28
#, python-brace-format
msgid ""
"A previous version used a DOI registered from {sitename}. This version "
"must also use a DOI from {sitename}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/components/pids.py:37
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/components/pids.py:46
#, python-brace-format
msgid ""
"A previous version was published with a DOI from an external provider or "
"without one. You cannot use a DOI registered from {sitename} for this "
"version."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/components/review.py:37
msgid ""
"You cannot delete a draft with an open review. Please cancel the review "
"first."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/github/metadata.py:59
msgid "No description provided."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/github/metadata.py:178
msgid "Citation schema is needed to load citation metadata."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/errors.py:22
#, python-brace-format
msgid "No configuration defined for PIDs {schemes}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/errors.py:33
#, python-format
msgid "Unknown PID provider %(provider)s for %(scheme)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:86
#, python-brace-format
msgid "Invalid {scheme}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:162
#, python-brace-format
msgid "A PID already exists for type {scheme}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:169
msgid "External identifier value is required."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:204
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:230
#, python-brace-format
msgid "PID not found for type {scheme}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/manager.py:251
msgid "Cannot discard a reserved or registered persistent identifier."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/providers/base.py:85
msgid "You must provide a pid value."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/providers/base.py:176
#, python-brace-format
msgid "{pid_type}:{identifier} already exists."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/providers/datacite.py:284
msgid "Missing publisher field required for DOI registration."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/providers/external.py:45
#, python-brace-format
msgid ""
"The prefix '{prefix}' is managed by {sitename}. Please supply an external"
" DOI or select 'No' to have a DOI generated for you."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/pids/providers/external.py:91
#, python-brace-format
msgid "Missing {scheme} for required field."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:58
msgid "Invalid review type."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:65
msgid "A review already exists for this record"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:69
msgid "You cannot create a review for an already published record."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:138
msgid "You cannot delete a review for a draft that has already been published."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:144
msgid "An open review cannot be deleted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/review/service.py:163
msgid "Must be a boolean, true or false"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/access.py:39
msgid "Embargo end date must be set to a future date."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/access.py:48
msgid "Embargo end date must be unset or in the past."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/access.py:65
#, python-brace-format
msgid "'{field_name}' must be either 'public' or 'restricted'"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/community_records.py:34
#, python-brace-format
msgid "Too many records passed, {max_number} max allowed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/community_records.py:51
#, python-brace-format
msgid "Duplicated records {rec_ids}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:74
msgid "Only one value is accepted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:76
msgid "Not a valid locale."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:88
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:92
#, python-brace-format
msgid "Invalid value. Choose one of {NAMES}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:115
msgid "Family name cannot be blank."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:120
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/schema.py:41
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/schema.py:36
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/schema.py:44
msgid "Name cannot be blank."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:156
msgid "Duplicated affiliations: "
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:215
#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:227
msgid "Not a valid URL."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:247
msgid "An existing id or a free text title must be present"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:252
msgid ""
"Only an existing id or free text title/description/link is accepted, but "
"not both cases at the same time"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:342
msgid ""
"At least one of ['geometry', 'place',                 identifiers', "
"'description'] must be present."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:381
msgid "Size cannot be a blank string."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/metadata.py:384
msgid "Format cannot be a blank string."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/record.py:44
msgid "Invalid persistent identifier scheme."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/record_communities.py:37
#, python-brace-format
msgid "Too many communities passed, {max_number} max allowed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/record_communities.py:54
#, python-brace-format
msgid "Duplicated communities {com_ids}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/services/schemas/parent/__init__.py:28
#, python-brace-format
msgid "Invalid persistent identifier scheme {scheme}."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:24
msgid ""
"Missing \"kid\" key with personal access token ID in JWT header of "
"resource access token."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:33
msgid ""
"\"kid\" JWT header value of resource access token not a valid personal "
"access token ID."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:41
msgid "Failed to decode resource access token."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:47
msgid "The resource access token is invalid."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:53
msgid "The resource access token subject is invalid."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:59
msgid "The resource access token is expired."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/errors.py:65
msgid "Resource Access Tokens feature is currently disabled."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_rdm_records/tokens/scopes.py:16
msgid "Allow generation of granular access JWT tokens."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records/admin.py:43
msgid "Revision"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records/admin.py:44
msgid "JSON"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records/admin.py:70
#, python-brace-format
msgid "Failed to delete record. {error}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/records/systemfields/entity_reference.py:46
#, python-format
msgid "Invalid reference for '%(key)s': %(obj)s"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:61
#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:62
msgid "Invalid query string syntax."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:63
msgid "Misconfigured search."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:74
msgid "Internal server error"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:120
msgid "Invalid querystring parameters."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:144
msgid "The persistent identifier is already registered."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:150
msgid "The persistent identifier does not exist."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:156
msgid "The persistent identifier is not registered."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:163
msgid "Not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:170
#, python-format
msgid "Facet %(vocabulary_id)s not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:183
msgid "Unable to decode JSON data in request body."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:189
#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:195
msgid "Not a valid value."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:204
msgid "The file upload transfer failed, please try again."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/resources/errors.py:211
msgid ""
"Uploading selected files will result in exceeding the max amount per "
"record."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:51
#, python-format
msgid ""
"Revision id provided(%(expected_revision_id)s) doesn't match record's "
"one(%(record_revision_id)s)"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:73
#, python-format
msgid "Facet %(vocab)s not found."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:83
#, python-format
msgid "Record '%(recid)s' has no file '%(file_key)s'."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:99
#, python-format
msgid "Record '%(recid)s' failed to upload file '%(file_key)s'."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/errors.py:116
#, python-brace-format
msgid ""
"Uploading the selected files would result in {files_count} files (max is "
"{max_files})."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/custom_fields/errors.py:37
#, python-format
msgid ""
"Namespace %(given_namespace)s is not valid for custom field "
"%(field_name)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/custom_fields/errors.py:54
#, python-format
msgid "Custom fields %(field_names)s are not configured."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/custom_fields/errors.py:70
#, python-format
msgid "Invalid argument %(arg_name)s passed when initializing custom field."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/files/service.py:274
msgid "File upload transfer failed."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/files/transfer.py:77
msgid "File size limit exceeded."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/files/transfer.py:103
msgid "Empty files are not accepted."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/components/files.py:89
msgid "You must first delete all files to set the record to be metadata-only."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/params/pagination.py:39
msgid "Invalid pagination parameters."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/params/querystr.py:30
msgid "You cannot specify both 'q' and 'suggest' parameters at the same time."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/params/querystr.py:41
msgid "Invalid 'suggest' parameter."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/params/sort.py:62
#, python-format
msgid "Invalid sort option '%(sort_option)s'."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/queryparser/transformer.py:128
#: .venv/lib/python3.13/site-packages/invenio_records_resources/services/records/queryparser/transformer.py:133
#, python-format
msgid "Invalid search field: %(field_name)s."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_rest/config.py:273
msgid "Most recent"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_records_rest/views.py:66
msgid "The syntax of the search query is invalid."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_theme/config.py:129
#: .venv/lib/python3.13/site-packages/invenio_theme/config.py:141
msgid "Invenio"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/ext.py:109
#, python-format
msgid "%(icon)s Profile"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:61
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:64
msgid "Username"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:63
#, python-brace-format
msgid "Required. {username_rules}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:66
msgid "Username not provided."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:72
msgid "Full name"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:79
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:32
msgid "Affiliations"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:98
msgid "Username is not available."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:131
msgid "Email address"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:145
msgid "Re-enter email address"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:147
msgid "Please re-enter your email address."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:154
msgid "Email addresses do not match."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:163
msgid "Resend verification email"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:204
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:49
msgid "Profile visibility"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:210
msgid ""
"Public profiles can be found by other users via searches on username, "
"full name and affiliation. Hidden profiles cannot be found by other "
"users."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:217
msgid "Email visibility"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:223
msgid ""
"Public email visibility enables your profile to be found by your email "
"address."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/forms.py:230
msgid "Preferences locale"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/validators.py:19
msgid ""
"Username must start with a letter, be at least three characters long and "
"only contain alphanumeric characters, dashes and underscores."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/views.py:113
msgid "Verification email sent."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/views.py:136
#, python-brace-format
msgid ""
"Profile was updated. We have sent a verification email to {email}. Please"
" check it."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/views.py:143
msgid "Profile was updated."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_userprofiles/views.py:152
msgid "Preferences were updated."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:72
#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:158
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:16
msgid "Domain"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:174
msgid "# Users"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:178
msgid "# Active"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:182
msgid "# Inactive"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:186
msgid "# Confirmed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:190
msgid "# Verified"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/config.py:194
msgid "# Blocked"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/forms.py:24
msgid "Notify me"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/forms.py:25
msgid "Turn on to enable notifications for relevant events."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/resources/domains/resource.py:29
msgid "Domain already exists."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/resources/users/config.py:66
msgid "User is locked due to concurrent running operation."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/schemas.py:147
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/schemas.py:151
msgid "Deleted user"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/schemas.py:160
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/schemas.py:164
msgid "System"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:19
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:24
msgid "Moderated"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:20
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:25
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:40
msgid "Verified"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:21
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:26
#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:42
msgid "Blocked"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:28
msgid "Flagged"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:30
msgid "Yes"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:31
msgid "No"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:44
msgid "Organisation"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/domains/facets.py:50
msgid "Top-level domain"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:21
msgid "Domain status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:37
msgid "Account status"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:41
msgid "Confirmed"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:43
msgid "Inactive"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:52
msgid "Profile"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_users_resources/services/users/facets.py:53
msgid "Full"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:68
msgid "PIC"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:69
msgid "EDMO"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/administration/views/vocabularies.py:38
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/config.py:179
msgid "Number of entries"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:30
msgid "Process ROR affiliations"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:31
msgid "Load ROR affiliations"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:68
msgid "Process ROR funders"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:69
msgid "Load ROR funders"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:106
msgid "Import awards from OpenAIRE"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:107
msgid "Import Awards OpenAIRE"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:141
msgid "Update awards from CORDIS"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:142
msgid "Update Awards CORDIS"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:169
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/jobs.py:170
msgid "Import ORCID data"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/administration/views/vocabularies.py:21
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/administration/views/vocabularies.py:24
msgid "Vocabulary Types"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/affiliations/schema.py:47
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/schema.py:69
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/schema.py:60
msgid "PID cannot be blank."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/config.py:49
msgid "Funders"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/datastreams.py:67
#, python-brace-format
msgid "Unknown OpenAIRE funder prefix {openaire_funder_prefix}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/datastreams.py:108
#, python-brace-format
msgid "Missing title attribute for award {award_id}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/datastreams.py:244
#, python-brace-format
msgid "No related legal basis programme found for project {project_id}"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/schema.py:52
msgid "Number cannot be blank."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/schema.py:100
msgid "An existing id or either number or title must be present."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/awards/schema.py:118
msgid "At least award or funder should be present."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/common/ror/datastreams.py:141
msgid "Id not found in ROR entry."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/common/ror/datastreams.py:173
msgid "Name with type ror_display not found in ROR entry."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/funders/schema.py:73
#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/schema.py:120
msgid "Missing PID."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/schema.py:76
msgid "A name or the family name together with the given name must be present."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/contrib/names/schema.py:90
msgid "Duplicated affiliations."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/records/models.py:84
#, python-format
msgid "No '%(banned_char)s' allowed in VocabularyScheme.id"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/components.py:29
msgid "The vocabulary type does not exists."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/schema.py:85
#, python-brace-format
msgid "An existing id or a free text {ftf_name} must be present."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/custom_fields/subject.py:57
msgid "Keywords and subjects"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/custom_fields/subject.py:59
msgid "The subjects related to the community"
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/custom_fields/subject.py:60
msgid "Search for a subject by name e.g. Psychology ..."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_vocabularies/services/custom_fields/subject.py:62
msgid "Search for subjects..."
msgstr ""

#: .venv/lib/python3.13/site-packages/invenio_webhooks/views.py:49
msgid "Allow notifications from external service."
msgstr ""

